---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: "Include kirill_zak.ansible_test_docker_helper"
      ansible.builtin.include_role:
        name: kirill_zak.ansible_test_docker_helper
        tasks_from: main.yml
